### ISSUE TITLE
Arda.Main is reading wrong sections in secrets.json

### ISSUE THREAD

**Issue by fabriciosanchez** [DXBrazil/Arda#12]
When Startup.Auth.cs try to read secrets in order to get informations about authentication, the application crashes.

**Comment by fcatae** [comment]
Does it fix it?
https://github.com/DXBrazil/Arda/commit/e89271a1679f77da12cf5c27eba233fb65685df4

**Comment by fabriciosanchez** [comment]
@fcatae exists a small difference between local User Secrets and that delivered by DevOps pipeline. I just did the equalization between it and now is evething ok.
