### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by ViniciusSouza** [DXBrazil/Arda#5]
- [x]  Appointment/My - The appointment list is not handling the field "Appointment date" as a Date to order making it dificult to keep on track the last appointment logged.

- [x] Fix - User Picture from Azure Active Directory is not being used

- [x] Coding Logging - Handle exception with Applicaiton Insights

**Comment by fcatae** [comment]
Split the issue into #15 , #16 , #17

**Comment by fcatae** [comment]
We are almost done - need testing

**Comment by fcatae** [comment]
Done.
