### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by fabioharams** [DXBrazil/Arda#62]
![image](https://cloud.githubusercontent.com/assets/17723872/24832452/17b25180-1c87-11e7-980d-a3b316f83954.png)

**Comment by fcatae** [comment]
@fabioharams, entra via HTTPS e veja se vai..

Precisamos implementar o redirect automático.

**Comment by fcatae** [comment]
Thanks for reporting the bug! 
It will be address in #63 - Implement automatic HTTPS redirection.
