### ISSUE TITLE
Url do arda 

### ISSUE THREAD

**Issue by wandelson** [DXBrazil/Arda#93]
Qual a URL da demo do ARDA ?

**Comment by fcatae** [comment]
Retiramos as duas versões que estavam online. Por enquanto, a melhor opção é usar o botão de deployment dos projetos:
https://github.com/fcatae/Arda-FellowshipRings (versão tipo senhor dos anéis)
https://github.com/dxbrazil/arda (botão deploy to azure)

Estamos trabalhando em algumas melhorias para voltar a versão de demo. Algum ponto específico que voce queira olhar?
